"""
Django settings for hw10 project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from typing import Any

from pydantic import ConfigDict, field_validator, EmailStr
from pydantic_settings import BaseSettings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


class Settings(BaseSettings):
    MONGO_USER: str
    MONGO_PASS: str
    MONGO_DB_NAME: str
    MONGO_DOMAIN: str
    SECRET_KEY: str
    DJANGO_DB_NAME: str
    DJANGO_USER: str
    DJANGO_PASSWORD: str
    DJANGO_HOST: str
    DJANGO_PORT: str
    EMAIL_BACKEND: str
    EMAIL_HOST: str
    EMAIL_PORT: int
    EMAIL_STARTTLS: bool
    EMAIL_USE_SSL: bool
    EMAIL_USE_TLS: bool
    EMAIL_HOST_USER: EmailStr
    EMAIL_HOST_PASSWORD: str
    DEFAULT_FROM_EMAIL: EmailStr

    # @field_validator("ALGORITHM")
    # @classmethod
    # def validate_algorithm(cls, v: Any):
    #     if v not in ["HS256", "HS512"]:
    #         raise ValueError("algorithm must be HS256 or HS512")
    #     return v

    model_config = ConfigDict(
        extra="ignore", env_file=f"{BASE_DIR}/.env", env_file_encoding="utf-8"
    )  # noqa
config = Settings()


# import configparser

# config = configparser.ConfigParser()
# config.read("quotes\config.ini")

mo_user = config.MONGO_USER
mo_pass = config.MONGO_PASS
mo_db_name = config.MONGO_DB_NAME
mo_domain = config.MONGO_DOMAIN


dj_user = config.DJANGO_USER
dj_pass = config.DJANGO_PASSWORD
dj_db_name = config.DJANGO_DB_NAME
dj_domain = config.DJANGO_HOST
dj_port = config.DJANGO_PORT


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-m4vgw*guyc(8kbzgpj%hp)v*87o*$+w4&p13y7%2g8ut^l=n^3'
SECRET_KEY = config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "quotes",
    "users",
    "django_mongoengine",
    "django_mongoengine.mongo_auth",
    "django_mongoengine.mongo_admin",
    # "debug_toolbar_mongo",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hw10.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hw10.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": dj_db_name,
        "USER": dj_user,
        "PASSWORD": dj_pass,
        "HOST": dj_domain,
        "PORT": dj_port,
    }
}

MONGODB_DATABASES = {
    "default": {
        "NAME": mo_db_name,
        "HOST": mo_domain,
        # "PORT": 27017,
        "USERNAME": mo_user,
        "PASSWORD": mo_pass,
        # "AUTHENTICATION_SOURCE": "admin",  # Якщо використовуєте аутентифікацію
        # "AUTHENTICATION_MECHANISM": "SCRAM-SHA-1",  # Якщо використовуєте аутентифікацію
        # Додаткові параметри, якщо потрібно
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = "/users/login"
LOGIN_REDIRECT_URL = "/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
#
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MONGODBFORMS_FIELDGENERATOR = 'myproject.fieldgenerator.GeneratorClass'
